%function Hd = FIRfiltDesign
%FIRFILTDESIGN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 28-Mar-2025 09:29:32

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 50000;  % Sampling Frequency

Fpass = 1500;              % Passband Frequency
Fstop = 2500;              % Stopband Frequency
Dpass = 0.028774368332;    % Passband Ripple
Dstop = 0.00056234132519;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
